import { describe, expect, it } from "vitest";

import { isShareViewable, shareState } from "@/lib/demo-share";

import type { DemoShareTableGateway } from "./share-gateway";
import type { DemoShareRow } from "./share-mapping";
import { createDemoShareRepository } from "./share-supabase";

/**
 * The repository against an in-memory gateway -- no network, no credentials.
 *
 * These assertions are mostly about the token and about revocation, because
 * this is the one store whose contents gate an unauthenticated route.
 */

class FakeGateway implements DemoShareTableGateway {
  rows: DemoShareRow[] = [];
  /** Set to make the next insert fail, standing in for a unique violation. */
  failInsert = false;

  async insertRow(row: DemoShareRow): Promise<void> {
    if (this.failInsert) throw new Error("demo_shares_token_unique");
    this.rows.push({ ...row });
  }
  async findRowByToken(token: string): Promise<DemoShareRow | null> {
    return this.rows.find((r) => r.token === token) ?? null;
  }
  async findRowById(id: string): Promise<DemoShareRow | null> {
    return this.rows.find((r) => r.id === id) ?? null;
  }
  async listRowsForDemo(demoId: string): Promise<DemoShareRow[]> {
    return this.rows
      .filter((r) => r.demo_id === demoId)
      .sort((a, b) => (a.created_at < b.created_at ? 1 : -1));
  }
  async markRevoked(id: string, revokedAt: string): Promise<void> {
    const row = this.rows.find((r) => r.id === id);
    if (row && row.revoked_at === null) row.revoked_at = revokedAt;
  }
}

const EXPIRES = "2026-12-01T00:00:00.000Z";

function repo(gateway = new FakeGateway(), nowIso = "2026-06-01T00:00:00.000Z") {
  return {
    gateway,
    store: createDemoShareRepository(gateway, { now: () => new Date(nowIso) }),
  };
}

describe("the token", () => {
  it("is generated by the repository, never supplied by the caller", async () => {
    // `CreateShareInput` has no token field. Asserted at runtime too, because
    // the compile-time guarantee is the point of the design.
    const { store } = repo();
    const share = await store.create({ demoId: "demo-1", expiresAt: EXPIRES, note: null });
    expect(share.token).toBeTruthy();
    expect(Object.keys({ demoId: "", expiresAt: "", note: null })).not.toContain("token");
  });

  it("carries real entropy", async () => {
    const { store } = repo();
    const share = await store.create({ demoId: "demo-1", expiresAt: EXPIRES, note: null });
    // 32 bytes base64url is 43 characters, and the mapper refuses under 32.
    expect(share.token.length).toBeGreaterThanOrEqual(43);
    expect(share.token).toMatch(/^[A-Za-z0-9_-]+$/);
  });

  it("is different for every share of the same demo", async () => {
    // Revoking one link must not silently revoke another handed to someone
    // else, which requires the tokens to be independent.
    const { store } = repo();
    const tokens = new Set<string>();
    for (let i = 0; i < 25; i += 1) {
      const share = await store.create({ demoId: "demo-1", expiresAt: EXPIRES, note: null });
      tokens.add(share.token);
    }
    expect(tokens.size).toBe(25);
  });

  it("is not derived from the demo id", async () => {
    const { store } = repo();
    const share = await store.create({
      demoId: "11111111-1111-4111-8111-111111111111",
      expiresAt: EXPIRES,
      note: null,
    });
    expect(share.token).not.toContain("1111");
    expect(share.token).not.toContain(share.demoId);
  });

  it("surfaces a collision as an error rather than retrying quietly", async () => {
    // At 32 bytes a collision means the generator is broken, not that we were
    // unlucky. Retrying would hide that.
    const gateway = new FakeGateway();
    gateway.failInsert = true;
    const { store } = repo(gateway);
    await expect(
      store.create({ demoId: "demo-1", expiresAt: EXPIRES, note: null }),
    ).rejects.toThrow(/could not create/i);
  });
});

describe("resolving a token", () => {
  it("finds a live share", async () => {
    const { store } = repo();
    const created = await store.create({ demoId: "demo-1", expiresAt: EXPIRES, note: null });
    expect(await store.findByToken(created.token)).toEqual(created);
  });

  it("returns null for a token that was never issued", async () => {
    const { store } = repo();
    expect(await store.findByToken("nope".repeat(12))).toBeNull();
  });

  it("returns an expired or revoked share rather than hiding it", async () => {
    // The caller decides what a visitor is told. Filtering here would make it
    // impossible to distinguish states in the operator's own view, where the
    // distinction genuinely matters.
    const { store } = repo();
    const created = await store.create({
      demoId: "demo-1",
      expiresAt: "2026-01-01T00:00:00.000Z",
      note: null,
    });
    const found = await store.findByToken(created.token);
    expect(found).not.toBeNull();
    expect(shareState(found!, new Date("2026-06-01T00:00:00.000Z"))).toBe("expired");
  });
});

describe("revoking", () => {
  it("marks a share revoked and stops it working", async () => {
    const { store } = repo();
    const created = await store.create({ demoId: "demo-1", expiresAt: EXPIRES, note: null });
    expect(isShareViewable(created, new Date("2026-06-02T00:00:00.000Z"))).toBe(true);

    const revoked = await store.revoke(created.id);
    expect(revoked?.revokedAt).toBe("2026-06-01T00:00:00.000Z");
    expect(isShareViewable(revoked!, new Date("2026-06-02T00:00:00.000Z"))).toBe(false);
  });

  it("keeps the original timestamp when revoked twice", async () => {
    // The moment it stopped working is the fact worth keeping, not the moment
    // somebody clicked the button a second time.
    const gateway = new FakeGateway();
    const first = createDemoShareRepository(gateway, {
      now: () => new Date("2026-06-01T00:00:00.000Z"),
    });
    const created = await first.create({ demoId: "demo-1", expiresAt: EXPIRES, note: null });
    await first.revoke(created.id);

    const later = createDemoShareRepository(gateway, {
      now: () => new Date("2026-07-01T00:00:00.000Z"),
    });
    const again = await later.revoke(created.id);
    expect(again?.revokedAt).toBe("2026-06-01T00:00:00.000Z");
  });

  it("returns null for an id that does not exist", async () => {
    const { store } = repo();
    expect(await store.revoke("no-such-share")).toBeNull();
  });

  it("does not touch any other share of the same demo", async () => {
    const { store } = repo();
    const a = await store.create({ demoId: "demo-1", expiresAt: EXPIRES, note: null });
    const b = await store.create({ demoId: "demo-1", expiresAt: EXPIRES, note: null });

    await store.revoke(a.id);

    expect((await store.findByToken(b.token))?.revokedAt).toBeNull();
  });
});

describe("the contract offers no way to weaken a link", () => {
  it("exposes only create, findByToken, listForDemo and revoke", async () => {
    // A token cannot be rewritten, an expiry cannot be extended, and a share
    // cannot be repointed at a different demo. Those are absent by design, so
    // their absence is asserted rather than assumed.
    const { store } = repo();
    expect(Object.keys(store).sort()).toEqual([
      "create",
      "findByToken",
      "listForDemo",
      "revoke",
    ]);
  });

  it("lists a demo's shares newest first", async () => {
    const gateway = new FakeGateway();
    const early = createDemoShareRepository(gateway, {
      now: () => new Date("2026-06-01T00:00:00.000Z"),
    });
    const late = createDemoShareRepository(gateway, {
      now: () => new Date("2026-06-05T00:00:00.000Z"),
    });
    await early.create({ demoId: "demo-1", expiresAt: EXPIRES, note: "first" });
    await late.create({ demoId: "demo-1", expiresAt: EXPIRES, note: "second" });

    expect((await early.listForDemo("demo-1")).map((s) => s.note)).toEqual(["second", "first"]);
  });
});
