-- Lead storage for the Business Lead Finder.
--
-- Mirrors the application's Lead shape: application-owned columns at the top
-- level, and the provider's latest snapshot as a single jsonb document. The
-- split is deliberate -- rediscovery replaces `provider` wholesale while id,
-- status and created_at survive by construction.
--
-- The four `*_dedupe` helper columns exist only so Postgres can enforce the
-- deduplication rules the application already implements. They are database
-- implementation details and are NOT part of the Lead TypeScript interface.
--
-- Never persisted here: the derived lead priority score, and per-search
-- metadata such as truncation. Both are request-level, derived data.
--
-- STRICT BY DESIGN. This is the first migration and has never been applied, so
-- it uses plain CREATE statements with no IF NOT EXISTS guards. Supabase already
-- records which migrations have run; this file should fail loudly if it meets an
-- unexpected pre-existing or partially-created `leads` table rather than quietly
-- adapting to a schema we did not author.

create table public.leads (
  -- Our own identifier, generated by the application. Never derived from a
  -- provider id, because provider ids can be retired or replaced.
  id uuid primary key,

  -- Application-owned fields. Status is deliberately minimal: this is not a
  -- CRM state machine and should not become one without a real reason.
  status text not null constraint leads_status_check check (status in ('new', 'reviewed')),
  created_at timestamptz not null,
  updated_at timestamptz not null,

  -- The provider's latest snapshot, replaced wholesale on rediscovery.
  provider jsonb not null,

  -- ---- dedupe helper columns (database implementation detail) -------------
  -- Denormalized from `provider` so Postgres can index and constrain them.
  -- The application also verifies on read that these agree with the snapshot.
  provider_source text not null,
  provider_external_id text not null,
  -- Accent-folded, lowercased, whitespace-collapsed by the application.
  normalized_name text not null,
  -- NULL when the provider gave no usable address. NULL is never a wildcard.
  normalized_address text null
);

-- PRIMARY dedupe identity: the same provider returning the same object again.
-- Scoped to the source because an external id is only unique within a provider.
create unique index leads_provider_identity_idx
  on public.leads (provider_source, provider_external_id);

-- SECONDARY dedupe: a business re-listed under a new provider id.
--
-- PARTIAL on purpose. Rows with a NULL normalized_address are excluded, so two
-- different businesses that share a name but have no address are never merged.
-- A missing address means "unknown", never "matches anything" -- a false merge
-- silently destroys a real lead, which is worse than carrying a duplicate.
--
-- Deliberately NOT scoped to provider_source: if two providers describe the
-- same business at the same address, that is one lead, not two.
create unique index leads_normalized_identity_idx
  on public.leads (normalized_name, normalized_address)
  where normalized_address is not null;

-- The dashboard lists leads and filters by status in the application layer;
-- this supports the common "newest first" read as the table grows.
create index leads_created_at_idx
  on public.leads (created_at desc);

-- ---- Security ------------------------------------------------------------
--
-- Two INDEPENDENT layers protect this table, and both are required:
--
--   1. PostgreSQL table privileges (GRANT/REVOKE)
--   2. Row Level Security
--
-- Postgres checks privileges FIRST. A role with no table grant is refused
-- before RLS is ever consulted, so grants are the outer gate and RLS the inner
-- one. Getting this order wrong is easy to miss: the secret key bypasses RLS,
-- but it cannot bypass a missing GRANT.
--
-- This project was created with "Automatically expose new tables" = OFF, so a
-- new table receives no Data API privileges by default. The grants below are
-- therefore not redundant -- without them the server-side client would be
-- refused access to its own table.

-- Browser-facing roles get nothing. Explicit even though the project setting
-- already withholds it, so the intent survives if that setting is ever changed.
revoke all on table public.leads from anon, authenticated;

-- The server-side client authenticates as service_role using
-- SUPABASE_SECRET_KEY. It needs exactly these four verbs and nothing more:
-- no TRUNCATE, no REFERENCES, no TRIGGER, and no schema-level rights.
grant select, insert, update, delete on table public.leads to service_role;

-- No sequence grant is required: `id` is an application-generated UUID and the
-- table has no serial or identity column, so there is no sequence to own.

-- RLS enabled with NO policies, deliberately.
--
-- With RLS on and no policy present, anon and authenticated can read and write
-- nothing even if a table grant were ever added by mistake -- the two layers
-- fail independently. service_role bypasses RLS, which is why its access is
-- controlled by the explicit grant above.
--
-- If a browser-facing policy is ever needed it must be added explicitly and
-- reviewed. It must never appear by accident.
alter table public.leads enable row level security;
